object frm_licenca: Tfrm_licenca
  Left = 0
  Top = 0
  Caption = 'Licen'#231'a'
  ClientHeight = 643
  ClientWidth = 1328
  Color = clWhite
  Ctl3D = False
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Segoe UI'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  WindowState = wsMaximized
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 17
  object pnlTotal: TPanel
    Left = 0
    Top = 0
    Width = 1328
    Height = 149
    Align = alTop
    BevelOuter = bvNone
    Padding.Left = 3
    Padding.Right = 3
    TabOrder = 0
    object pnl_tit_geral: TPanel
      Left = 3
      Top = 0
      Width = 1322
      Height = 30
      Align = alTop
      Alignment = taLeftJustify
      BevelOuter = bvNone
      BorderStyle = bsSingle
      Caption = ' LICEN'#199'AS / CONDICIONANTES'
      Color = 12159842
      Ctl3D = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -19
      Font.Name = 'Segoe UI Semibold'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentCtl3D = False
      ParentFont = False
      TabOrder = 0
      OnMouseDown = pnl_tit_geralMouseDown
    end
    object pnl_geral: TPanel
      Left = 3
      Top = 98
      Width = 1322
      Height = 51
      Align = alClient
      BevelOuter = bvNone
      BorderStyle = bsSingle
      ParentBackground = False
      TabOrder = 1
      object Label1: TLabel
        Left = 10
        Top = 4
        Width = 12
        Height = 17
        Caption = 'ID'
      end
      object lbl_cnpj_cpf: TLabel
        Left = 75
        Top = 4
        Width = 63
        Height = 17
        Caption = 'CNPJ / CPF'
      end
      object Label4: TLabel
        Left = 210
        Top = 4
        Width = 123
        Height = 17
        Caption = 'Nome / Raz'#227'o Social'
      end
      object Label5: TLabel
        Left = 614
        Top = 4
        Width = 47
        Height = 17
        Caption = 'Fantasia'
      end
      object Label2: TLabel
        Left = 894
        Top = 4
        Width = 54
        Height = 17
        Caption = 'Atividade'
      end
      object edt_id: TwwDBEdit
        Left = 10
        Top = 21
        Width = 60
        Height = 23
        TabStop = False
        BorderStyle = bsNone
        Color = clBtnFace
        DataField = 'id'
        DataSource = dts_cliente
        Frame.Enabled = True
        Frame.NonFocusBorders = [efLeftBorder, efTopBorder, efRightBorder, efBottomBorder]
        Frame.FocusStyle = efsFrameEtched
        Frame.NonFocusStyle = efsFrameEtched
        ReadOnly = True
        TabOrder = 0
        UnboundDataType = wwDefault
        WantReturns = False
        WordWrap = False
      end
      object edt_cnpj_cpf: TwwDBEdit
        Left = 75
        Top = 21
        Width = 130
        Height = 23
        TabStop = False
        BorderStyle = bsNone
        Color = clBtnFace
        DataField = 'cnpj'
        DataSource = dts_cliente
        Frame.Enabled = True
        Frame.NonFocusBorders = [efLeftBorder, efTopBorder, efRightBorder, efBottomBorder]
        Frame.FocusStyle = efsFrameEtched
        Frame.NonFocusStyle = efsFrameEtched
        ReadOnly = True
        TabOrder = 1
        UnboundDataType = wwDefault
        WantReturns = False
        WordWrap = False
      end
      object edt_nome: TwwDBEdit
        Left = 210
        Top = 21
        Width = 400
        Height = 23
        TabStop = False
        BorderStyle = bsNone
        CharCase = ecUpperCase
        Color = clBtnFace
        DataField = 'nome'
        DataSource = dts_cliente
        Frame.Enabled = True
        Frame.NonFocusBorders = [efLeftBorder, efTopBorder, efRightBorder, efBottomBorder]
        Frame.FocusStyle = efsFrameEtched
        Frame.NonFocusStyle = efsFrameEtched
        ReadOnly = True
        TabOrder = 2
        UnboundDataType = wwDefault
        WantReturns = False
        WordWrap = False
      end
      object edt_fantasia: TwwDBEdit
        Left = 615
        Top = 21
        Width = 274
        Height = 23
        TabStop = False
        BorderStyle = bsNone
        CharCase = ecUpperCase
        Color = clBtnFace
        DataField = 'fantasia'
        DataSource = dts_cliente
        Frame.Enabled = True
        Frame.NonFocusBorders = [efLeftBorder, efTopBorder, efRightBorder, efBottomBorder]
        Frame.FocusStyle = efsFrameEtched
        Frame.NonFocusStyle = efsFrameEtched
        ReadOnly = True
        TabOrder = 3
        UnboundDataType = wwDefault
        WantReturns = False
        WordWrap = False
      end
      object edt_atividade: TwwDBEdit
        Left = 894
        Top = 21
        Width = 274
        Height = 23
        TabStop = False
        BorderStyle = bsNone
        CharCase = ecUpperCase
        Color = clBtnFace
        DataField = 'atividade'
        DataSource = dts_cliente
        Frame.Enabled = True
        Frame.NonFocusBorders = [efLeftBorder, efTopBorder, efRightBorder, efBottomBorder]
        Frame.FocusStyle = efsFrameEtched
        Frame.NonFocusStyle = efsFrameEtched
        ReadOnly = True
        TabOrder = 4
        UnboundDataType = wwDefault
        WantReturns = False
        WordWrap = False
      end
    end
    object Panel6: TPanel
      Left = 3
      Top = 30
      Width = 1322
      Height = 48
      Align = alTop
      BevelOuter = bvNone
      BorderStyle = bsSingle
      TabOrder = 2
      DesignSize = (
        1320
        46)
      object btn_ok: TSpeedButton
        Left = 1218
        Top = 4
        Width = 36
        Height = 36
        Hint = 'Confirmar'
        Anchors = [akTop, akRight]
        Flat = True
        Glyph.Data = {
          F6120000424DF612000000000000360000002800000028000000280000000100
          180000000000C0120000C30E0000C30E00000000000000000000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFBFDFCB5DFBC80C88A86CB90CCE9D0FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FBF669
          BF7634A84534A84534A84534A845A6D8ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FBF663BC7034A84534A84534A845
          34A84534A84534A845A6D8ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF5FBF663BC7034A84534A84534A84534A84534A84534A84534A8
          4534A845A6D8ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FBF663BC
          7034A84534A84534A84534A84534A84534A84534A84534A84534A84534A845A6
          D8ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FBF663BC7034A84534A84534A84534
          A84534A84534A84534A84534A84534A84534A84534A84534A845A6D8ADFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFF5FBF663BC7034A84534A84534A84534A84534A84534A84534A845
          34A84534A84534A84534A84534A84534A84534A845A6D8ADFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FBF663BC70
          34A84534A84534A84534A84534A84534A84534A84534A84534A84534A84534A8
          4534A84534A84534A84534A84534A845A6D8ADFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FBF663BC7034A84534A84534A84534A8
          4534A84534A84534A84534A84540AD5034A84534A84534A84534A84534A84534
          A84534A84534A84534A845A6D8ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFF5FBF663BC7034A84534A84534A84534A84534A84534A84534A84534
          A84547B056DFF1E2A6D8AD34A84534A84534A84534A84534A84534A84534A845
          34A84534A845A6D8ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF86CB9034
          A84534A84534A84534A84534A84534A84534A84534A84547B056DFF1E2FFFFFF
          FFFFFFA6D8AD34A84534A84534A84534A84534A84534A84534A84534A84534A8
          45A6D8ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FBF637A94734A84534A84534A845
          34A84534A84534A84534A84547B056DFF1E2FFFFFFFFFFFFFFFFFFFFFFFFA6D8
          AD34A84534A84534A84534A84534A84534A84534A84534A84534A845A6D8ADFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFE5F4E734A84534A84534A84534A84534A84534A84534A8
          4547B056DFF1E2FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA6D8AD34A84534
          A84534A84534A84534A84534A84534A84534A84534A845A6D8ADFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFBFDFC47B05634A84534A84534A84534A84534A84547B056DFF1E2FFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA6D8AD34A84534A84534A845
          34A84534A84534A84534A84534A84534A845A6D8ADFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB6DFBC34
          A84534A84534A84534A84547B056DFF1E2FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA6D8AD34A84534A84534A84534A84534A8
          4534A84534A84534A84534A845A6D8ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC9E8CD73C37F63BC70
          86CB90E5F4E7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFA6D8AD34A84534A84534A84534A84534A84534A84534
          A84534A84534A845A6D8ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFA6D8AD34A84534A84534A84534A84534A84534A84534A84534A845
          34A845B9E1BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          A6D8AD34A84534A84534A84534A84534A84534A84534A84534A84560BB6DFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA6D8AD34A8
          4534A84534A84534A84534A84534A84534A8454DB25CFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA6D8AD34A84534A84534
          A84534A84534A84534A8456DC079FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA6D8AD34A84534A84534A84534A845
          3AAA4AD5EDD9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFC9E8CD66BE734DB35C73C37FD5EDD9FFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
        ParentShowHint = False
        ShowHint = True
        OnClick = btn_okClick
        ExplicitLeft = 1234
      end
      object btnCancelar: TSpeedButton
        Left = 1256
        Top = 4
        Width = 36
        Height = 36
        Hint = 'N'#227'o Confirmar'
        Anchors = [akTop, akRight]
        Flat = True
        Glyph.Data = {
          F6120000424DF612000000000000360000002800000028000000280000000100
          180000000000C0120000C30E0000C30E00000000000000000000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFEAEAFFDCDCFFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFECECFFDCDCFFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFF
          9090FF5757FF5757FF6E6EFFDCDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFF9595FF5757FF5757FF69
          69FFD7D7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFADADFF5757FF5757FF5757
          FF5757FF5E5EFFD7D7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFCFCFF8D8DFF5757FF5757FF5757FF5757FF6969FFF9F9FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFF7979FF5757FF5757FF5757FF5757FF5757FF5E
          5EFFD7D7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFF
          8D8DFF5757FF5757FF5757FF5757FF5757FF5757FFDADAFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFF8888FF5757FF5757FF5757FF5757FF5757FF5757FF5E5EFFD7D7FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFF8D8DFF5757FF5757FF5757
          FF5757FF5757FF5757FF5757FFE7E7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD7D7FF
          5959FF5757FF5757FF5757FF5757FF5757FF5757FF5E5EFFD7D7FFFFFFFFFFFF
          FFFFFFFFFFFFFFFCFCFF8D8DFF5757FF5757FF5757FF5757FF5757FF5757FF57
          57FF8E8EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7C7FF5959FF5757
          FF5757FF5757FF5757FF5757FF5757FF5E5EFFD7D7FFFFFFFFFFFFFFFCFCFF8D
          8DFF5757FF5757FF5757FF5757FF5757FF5757FF5757FF7E7EFFF7F7FFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7C7FF5959FF5757FF5757FF57
          57FF5757FF5757FF5757FF5E5EFFD7D7FFFCFCFF8D8DFF5757FF5757FF5757FF
          5757FF5757FF5757FF5757FF8E8EFFF7F7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFC7C7FF5959FF5757FF5757FF5757FF5757FF
          5757FF5757FF5E5EFF8383FF5757FF5757FF5757FF5757FF5757FF5757FF5757
          FF8E8EFFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFC7C7FF5959FF5757FF5757FF5757FF5757FF5757FF5757
          FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF8E8EFFFCFCFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFC7C7FF5959FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF57
          57FF5757FF5757FF5757FF8E8EFFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7
          C7FF5959FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF
          8E8EFFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC5C5FF5757FF
          5757FF5757FF5757FF5757FF5757FF5757FF5757FF8989FFFCFCFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFF8D8DFF5757FF5757FF5757FF5757
          FF5757FF5757FF5757FF5757FF6666FFE4E4FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFCFCFF8D8DFF5757FF5757FF5757FF5757FF5757FF5757FF5757FF57
          57FF5757FF5757FF6666FFE4E4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFF8D8DFF57
          57FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF
          5757FF6666FFE4E4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFF8D8DFF5757FF5757FF5757FF5757FF
          5757FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF6666
          FFE4E4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFF7F7FF7E7EFF5757FF5757FF5757FF5757FF5757FF5757FF5757FF8E8E
          FFC5C5FF5959FF5757FF5757FF5757FF5757FF5757FF5757FF6666FFE4E4FFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7F7FF7E7EFF5757
          FF5757FF5757FF5757FF5757FF5757FF5757FF8E8EFFFCFCFFFFFFFFC7C7FF59
          59FF5757FF5757FF5757FF5757FF5757FF5757FF6666FFE4E4FFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FF7E7EFF5757FF5757FF5757FF5757FF57
          57FF5757FF5757FF8E8EFFFCFCFFFFFFFFFFFFFFFFFFFFC7C7FF5959FF5757FF
          5757FF5757FF5757FF5757FF5757FF6666FFE4E4FFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFA5A5FF5757FF5757FF5757FF5757FF5757FF5757FF5757FF8E8EFF
          FCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7C7FF5959FF5757FF5757FF5757
          FF5757FF5757FF5757FF7676FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7373FF
          5757FF5757FF5757FF5757FF5757FF5757FF8E8EFFFCFCFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFC7C7FF5959FF5757FF5757FF5757FF5757FF57
          57FF5757FFE2E2FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7E7EFF5757FF5757FF5757
          FF5757FF5757FF8E8EFFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFC7C7FF5959FF5757FF5757FF5757FF5757FF5757FFF1F1FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFCDCDFF5757FF5757FF5757FF5757FF8E8EFFFC
          FCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFC7C7FF5959FF5757FF5757FF5757FF9B9BFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFCFCFFF8686FF7979FFB0B0FFFCFCFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD5D5
          FF8989FF7979FFADADFFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
        ParentShowHint = False
        ShowHint = True
        OnClick = btnCancelarClick
        ExplicitLeft = 1272
      end
      object toolbar: TToolBar
        Left = 0
        Top = 0
        Width = 141
        Height = 46
        Align = alLeft
        AutoSize = True
        ButtonHeight = 46
        ButtonWidth = 47
        Caption = 'Novo'
        DisabledImages = dtm_images.img_40
        Images = dtm_images.img_40
        ParentShowHint = False
        ShowHint = True
        TabOrder = 0
        object btn_recarregar: TToolButton
          Left = 0
          Top = 0
          Caption = 'Novo'
          ImageIndex = 17
          OnClick = btn_recarregarClick
        end
        object ToolButton1: TToolButton
          Left = 47
          Top = 0
          Caption = 'Editar'
          DropdownMenu = pop_carregar
          ImageIndex = 18
          OnClick = btn_editarClick
        end
        object ToolButton3: TToolButton
          Left = 94
          Top = 0
          Caption = 'Excluir'
          DropdownMenu = pop_abrir
          ImageIndex = 15
          OnClick = btn_excluirClick
        end
      end
    end
    object Panel7: TPanel
      Left = 3
      Top = 78
      Width = 1322
      Height = 20
      Align = alTop
      Alignment = taLeftJustify
      BevelOuter = bvNone
      BorderStyle = bsSingle
      Caption = ' EMPRESA'
      Color = 12159842
      Ctl3D = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI Semibold'
      Font.Style = [fsBold]
      Padding.Right = 1
      ParentBackground = False
      ParentCtl3D = False
      ParentFont = False
      TabOrder = 3
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 149
    Width = 1328
    Height = 143
    Align = alTop
    BevelOuter = bvNone
    Color = clWhite
    Padding.Left = 3
    Padding.Top = 3
    Padding.Right = 2
    Padding.Bottom = 3
    ParentBackground = False
    TabOrder = 1
    object Panel3: TPanel
      Left = 3
      Top = 3
      Width = 1323
      Height = 20
      Align = alTop
      Alignment = taLeftJustify
      BevelOuter = bvNone
      BorderStyle = bsSingle
      Caption = ' LICEN'#199'A'
      Color = 12159842
      Ctl3D = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI Semibold'
      Font.Style = [fsBold]
      Padding.Right = 1
      ParentBackground = False
      ParentCtl3D = False
      ParentFont = False
      TabOrder = 0
    end
    object grd: TwwDBGrid
      Left = 3
      Top = 23
      Width = 1323
      Height = 117
      ControlType.Strings = (
        'id_tipo_licenca;CustomEdit;cmb_tipo;T'
        'id_orgao;CustomEdit;cmb_orgao;T'
        'assinatura;CustomEdit;edt_assinou;F'
        'id_municipio;CustomEdit;cmb_municipio;T'
        'renovada;CheckBox;S;N')
      Selected.Strings = (
        'id_tipo_licenca'#9'9'#9'TIPO'#9'F'
        'id_orgao'#9'10'#9#211'RG'#195'O'#9'F'
        'numero'#9'30'#9'LICEN'#199'A'#9'F'
        'processo'#9'30'#9'PROCESSO'#9'F'
        'dt_ini'#9'12'#9'IN'#205'CIO'#9'F'
        'dt_venc'#9'12'#9'VENCIMENTO'#9'F'
        'id_municipio'#9'20'#9'MUNIC'#205'PIO'#9'F'
        'dt_solic'#9'12'#9'DT.SOLIC'#9'F'
        'prazo'#9'10'#9'PRAZO'#9'F'
        'renovada'#9'1'#9'REN.'#9'F')
      IniAttributes.Delimiter = ';;'
      TitleColor = clBtnFace
      FixedCols = 0
      ShowHorzScrollBar = True
      Align = alClient
      DataSource = dts_licenca
      TabOrder = 1
      TitleAlignment = taLeftJustify
      TitleFont.Charset = ANSI_CHARSET
      TitleFont.Color = clWindowText
      TitleFont.Height = -13
      TitleFont.Name = 'Segoe UI'
      TitleFont.Style = []
      TitleLines = 1
      TitleButtons = False
      UseTFields = False
    end
    object cmb_tipo: TwwDBLookupCombo
      Left = 24
      Top = 69
      Width = 67
      Height = 23
      CharCase = ecUpperCase
      DropDownAlignment = taLeftJustify
      Selected.Strings = (
        'sigla'#9'8'#9'TIPO'#9'F')
      DataField = 'id_tipo_licenca'
      DataSource = dts_licenca
      LookupTable = qry_tipo
      LookupField = 'id'
      Style = csDropDownList
      TabOrder = 2
      AutoDropDown = True
      ShowButton = True
      PreciseEditRegion = False
      AllowClearKey = False
      ShowMatchText = True
    end
    object cmb_orgao: TwwDBLookupCombo
      Left = 84
      Top = 69
      Width = 74
      Height = 23
      DropDownAlignment = taLeftJustify
      Selected.Strings = (
        'sigla'#9'8'#9#211'RG'#195'O'#9'F')
      DataField = 'id_orgao'
      DataSource = dts_licenca
      LookupTable = qry_orgao
      LookupField = 'id'
      Style = csDropDownList
      TabOrder = 3
      AutoDropDown = True
      ShowButton = True
      UseTFields = False
      PreciseEditRegion = False
      AllowClearKey = False
      ShowMatchText = True
    end
    object cmb_municipio: TwwDBLookupCombo
      Left = 661
      Top = 81
      Width = 249
      Height = 23
      DropDownAlignment = taLeftJustify
      Selected.Strings = (
        'nome'#9'100'#9'MUNIC'#205'PIO'#9'F')
      DataField = 'id_municipio'
      DataSource = dts_licenca
      LookupTable = qry_municipio
      LookupField = 'id'
      Style = csDropDownList
      TabOrder = 4
      AutoDropDown = True
      ShowButton = True
      UseTFields = False
      PreciseEditRegion = False
      AllowClearKey = False
      ShowMatchText = True
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 292
    Width = 1328
    Height = 351
    Align = alClient
    BevelOuter = bvNone
    Color = clWhite
    Padding.Left = 3
    Padding.Right = 3
    Padding.Bottom = 3
    ParentBackground = False
    TabOrder = 2
    object grd_condicionante: TwwDBGrid
      Left = 3
      Top = 66
      Width = 857
      Height = 282
      ControlType.Strings = (
        'id_responsavel;CustomEdit;cmb_responsavel;F'
        'id_executor;CustomEdit;cmb_executor;F'
        'cumprida;CheckBox;S;N'
        'Img_protocolo;CheckBox;true;false')
      Selected.Strings = (
        'numero'#9'6'#9'N'#186#9'F'
        'categoria'#9'13'#9'CATEGORIA'#9'F'
        'prazo'#9'3'#9'PRAZO'#9'F'
        'dt_aviso'#9'11'#9'AVISO'#9'F'
        'dt_venc'#9'11'#9'VENC.'#9'F'
        'solic_prazo'#9'11'#9'SOL.PRAZO'#9'F'
        'solic_desconsid'#9'11'#9'SOL.DESC'#9'F'
        'solic_subst'#9'11'#9'SOL.SUBS'#9'F'
        'dt_cumprimento'#9'11'#9'DT.CUMP.'#9'F'
        'id_responsavel'#9'10'#9'RESP.'#9'F'
        'Img_protocolo'#9'5'#9'PRO'#9'F'
        'cumprida'#9'2'#9'OK'#9'F')
      IniAttributes.Delimiter = ';;'
      TitleColor = clBtnFace
      FixedCols = 0
      ShowHorzScrollBar = True
      Align = alLeft
      DataSource = dts_condicionante
      ReadOnly = True
      TabOrder = 2
      TitleAlignment = taLeftJustify
      TitleFont.Charset = ANSI_CHARSET
      TitleFont.Color = clWindowText
      TitleFont.Height = -13
      TitleFont.Name = 'Segoe UI'
      TitleFont.Style = []
      TitleLines = 1
      TitleButtons = False
      UseTFields = False
      OnDblClick = grd_condicionanteDblClick
      OnEnter = grd_condicionanteEnter
    end
    object pnl_tit_detalhe: TPanel
      Left = 3
      Top = 0
      Width = 1322
      Height = 20
      Align = alTop
      Alignment = taLeftJustify
      BevelOuter = bvNone
      BorderStyle = bsSingle
      Caption = ' CONDICIONANTE'
      Color = 12159842
      Ctl3D = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI Semibold'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentCtl3D = False
      ParentFont = False
      TabOrder = 0
    end
    object Panel4: TPanel
      Left = 860
      Top = 66
      Width = 465
      Height = 282
      Align = alClient
      BevelOuter = bvNone
      BorderStyle = bsSingle
      TabOrder = 1
      object Panel5: TPanel
        Left = 0
        Top = 0
        Width = 463
        Height = 21
        Align = alTop
        BevelOuter = bvNone
        Caption = 'DESCRI'#199#195'O'
        TabOrder = 0
      end
      object mmo_desc_condicionante: TDBMemo
        Left = 0
        Top = 21
        Width = 463
        Height = 259
        Align = alClient
        BevelInner = bvNone
        BevelOuter = bvNone
        BorderStyle = bsNone
        Ctl3D = False
        DataField = 'descricao'
        DataSource = dts_condicionante
        ParentCtl3D = False
        TabOrder = 1
      end
    end
    object cmb_responsavel: TwwDBComboBox
      Left = 75
      Top = 180
      Width = 121
      Height = 23
      ShowButton = True
      Style = csDropDown
      MapList = True
      AllowClearKey = False
      DataField = 'id_responsavel'
      DataSource = dts_condicionante
      DropDownCount = 8
      ItemHeight = 0
      Items.Strings = (
        'ECOPLAN'#9'1'
        'CLIENTE'#9'2')
      Sorted = False
      TabOrder = 3
      UnboundDataType = wwDefault
    end
    object ToolBar2: TToolBar
      Left = 3
      Top = 20
      Width = 1322
      Height = 46
      AutoSize = True
      ButtonHeight = 46
      ButtonWidth = 47
      Color = clWhite
      DisabledImages = dtm_images.img_40_des
      Images = dtm_images.img_40
      Indent = 5
      List = True
      ParentColor = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 4
      Transparent = False
      Wrapable = False
      object btn_nova: TToolButton
        Left = 5
        Top = 0
        Hint = 'Nova Condicionante'
        Caption = 'Nova'
        ImageIndex = 2
        ParentShowHint = False
        ShowHint = True
        OnClick = btn_novaClick
      end
      object btn_editar: TToolButton
        Left = 52
        Top = 0
        Hint = 'Editar Condicionante'
        Caption = 'Editar'
        ImageIndex = 4
        ParentShowHint = False
        ShowHint = True
        OnClick = btn_editarClick
      end
      object btn_excluir: TToolButton
        Left = 99
        Top = 0
        Hint = 'Excluir Condicionante'
        Caption = 'btn_excluir'
        ImageIndex = 3
        ParentShowHint = False
        ShowHint = True
        OnClick = btn_excluirClick
      end
      object btn_salvar: TToolButton
        Left = 146
        Top = 0
        Hint = 'Salvar Condicionante'
        Caption = 'Salvar'
        ImageIndex = 5
        ParentShowHint = False
        ShowHint = True
        OnClick = btn_salvarClick
      end
      object ToolButton2: TToolButton
        Left = 193
        Top = 0
        Width = 8
        Caption = 'ToolButton2'
        ImageIndex = 8
        Style = tbsSeparator
      end
      object btn_confirmar: TToolButton
        Left = 201
        Top = 0
        Hint = 'Cumprir Condicionante'
        Caption = 'Cumprir'
        ImageIndex = 7
        ParentShowHint = False
        ShowHint = True
        OnClick = btn_confirmarClick
      end
      object btn_prazo: TToolButton
        Left = 248
        Top = 0
        Hint = 'Solicita'#231#227'o de Prazo'
        Caption = 'btn_prazo'
        ImageIndex = 19
        OnClick = btn_prazoClick
      end
      object btn_solic_descosid: TToolButton
        Left = 295
        Top = 0
        Hint = 'Solicita'#231#227'o de Desconsidera'#231#227'o'
        Caption = 'btn_solic_descosid'
        ImageIndex = 21
        OnClick = btn_solic_descosidClick
      end
      object btn_subst: TToolButton
        Left = 342
        Top = 0
        Hint = 'Solicita'#231#227'o de Substitui'#231#227'o'
        Caption = 'btn_subst'
        ImageIndex = 22
        OnClick = btn_substClick
      end
      object btn_prot_cond: TToolButton
        Left = 389
        Top = 0
        Hint = 'Abrir Protocolo Carregado'
        Caption = 'btn_prot_cond'
        ImageIndex = 15
        ParentShowHint = False
        ShowHint = True
        OnClick = btn_prot_condClick
      end
    end
  end
  object dts_licenca: TDataSource
    DataSet = dse_licenca
    Left = 1249
    Top = 180
  end
  object dts_cliente: TDataSource
    AutoEdit = False
    DataSet = qry_cliente
    Left = 1162
    Top = 220
  end
  object dts_condicionante: TDataSource
    DataSet = dse_condicionante
    Left = 350
    Top = 412
  end
  object qry_cliente: TUniQuery
    Connection = dtm_dados.mysql_conn
    SQL.Strings = (
      'select '
      '    p.id,'
      '    p.cnpj,'
      '    p.cpf,'
      '    p.nome,'
      '    p.fantasia,'
      '    a.nome as atividade,'
      '    a.id as id_atividade'
      'from pessoa p'
      '    left join cliente_atividade ca'
      '        on ca.id_cliente = p.id'
      '    left join atividade a'
      '        on a.id = ca.id_atividade'
      'where p.id = :id_cliente'
      '    and a.id = :id_atividade')
    Left = 1190
    Top = 220
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'id_cliente'
      end
      item
        DataType = ftUnknown
        Name = 'id_atividade'
      end>
  end
  object dse_licenca: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO licenca'
      
        '  (id, id_tipo_licenca, id_atividade, id_orgao, numero, dt_ini, ' +
        'dt_venc, assinatura, id_cliente, id_municipio, descricao, proces' +
        'so, renovada, prazo, dt_solic)'
      'VALUES'
      
        '  (:id, :id_tipo_licenca, :id_atividade, :id_orgao, :numero, :dt' +
        '_ini, :dt_venc, :assinatura, :id_cliente, :id_municipio, :descri' +
        'cao, :processo, :renovada, :prazo, :dt_solic)')
    SQLDelete.Strings = (
      'DELETE FROM licenca'
      'WHERE'
      '  id = :Old_id')
    SQLUpdate.Strings = (
      'UPDATE licenca'
      'SET'
      
        '  id = :id, id_tipo_licenca = :id_tipo_licenca, id_atividade = :' +
        'id_atividade, id_orgao = :id_orgao, numero = :numero, dt_ini = :' +
        'dt_ini, dt_venc = :dt_venc, assinatura = :assinatura, id_cliente' +
        ' = :id_cliente, id_municipio = :id_municipio, descricao = :descr' +
        'icao, processo = :processo, renovada = :renovada, prazo = :prazo' +
        ', dt_solic = :dt_solic'
      'WHERE'
      '  id = :Old_id')
    SQLRefresh.Strings = (
      
        'SELECT id, id_tipo_licenca, id_atividade, id_orgao, numero, dt_i' +
        'ni, dt_venc, assinatura, id_cliente, id_municipio, descricao, pr' +
        'ocesso, renovada, prazo, dt_solic FROM licenca'
      'WHERE'
      '  id = :id')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM (SELECT * FROM licenca'
      ')')
    Connection = dtm_dados.mysql_conn
    SQL.Strings = (
      'select * '
      'from licenca '
      'where id_cliente = :id_cliente'
      '    and id_atividade = :id_atividade')
    Options.StrictUpdate = False
    AfterScroll = dse_licencaAfterScroll
    OnNewRecord = dse_licencaNewRecord
    Left = 1277
    Top = 180
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'id_cliente'
      end
      item
        DataType = ftUnknown
        Name = 'id_atividade'
      end>
    object dse_licencaid: TIntegerField
      FieldName = 'id'
    end
    object dse_licencaid_tipo_licenca: TIntegerField
      FieldName = 'id_tipo_licenca'
      Required = True
    end
    object dse_licencaid_atividade: TIntegerField
      FieldName = 'id_atividade'
    end
    object dse_licencaid_orgao: TIntegerField
      FieldName = 'id_orgao'
      Required = True
    end
    object dse_licencanumero: TStringField
      FieldName = 'numero'
      Required = True
      Size = 60
    end
    object dse_licencadt_ini: TDateField
      FieldName = 'dt_ini'
      Required = True
    end
    object dse_licencadt_venc: TDateField
      FieldName = 'dt_venc'
    end
    object dse_licencaassinatura: TStringField
      FieldName = 'assinatura'
      Size = 120
    end
    object dse_licencaid_cliente: TIntegerField
      FieldName = 'id_cliente'
    end
    object dse_licencaid_municipio: TIntegerField
      FieldName = 'id_municipio'
    end
    object dse_licencadescricao: TMemoField
      FieldName = 'descricao'
      BlobType = ftMemo
    end
    object dse_licencaprocesso: TStringField
      FieldName = 'processo'
      Size = 60
    end
    object dse_licencarenovada: TStringField
      FieldName = 'renovada'
      Size = 1
    end
    object dse_licencaprazo: TIntegerField
      FieldName = 'prazo'
    end
    object dse_licencadt_solic: TDateField
      FieldName = 'dt_solic'
    end
  end
  object qry_tipo: TUniQuery
    Connection = dtm_dados.mysql_conn
    Transaction = tra
    SQL.Strings = (
      'select id, sigla '
      'from tipo_licenca'
      'order by nome')
    Left = 56
    Top = 130
  end
  object qry_orgao: TUniQuery
    Connection = dtm_dados.mysql_conn
    Transaction = tra
    SQL.Strings = (
      'select id, sigla'
      'from orgao_ambiental'
      'order by nome ')
    Left = 120
    Top = 130
  end
  object qry_municipio: TUniQuery
    Connection = dtm_dados.mysql_conn
    SQL.Strings = (
      'select id, nome'
      'from municipio'
      'order by nome')
    Left = 927
    Top = 130
  end
  object dse_condicionante: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO condicionante'
      
        '  (id, id_licenca, numero, descricao, cumprida, dt_venc, dt_cump' +
        'rimento, dt_aviso, id_responsavel, id_executor, protocolo, id_ca' +
        'tegoria, prazo, solic_prazo, solic_desconsid, solic_subst)'
      'VALUES'
      
        '  (:id, :id_licenca, :numero, :descricao, :cumprida, :dt_venc, :' +
        'dt_cumprimento, :dt_aviso, :id_responsavel, :id_executor, :proto' +
        'colo, :id_categoria, :prazo, :solic_prazo, :solic_desconsid, :so' +
        'lic_subst)')
    SQLDelete.Strings = (
      'DELETE FROM condicionante'
      'WHERE'
      '  id = :Old_id')
    SQLUpdate.Strings = (
      'UPDATE condicionante'
      'SET'
      
        '  id = :id, id_licenca = :id_licenca, numero = :numero, descrica' +
        'o = :descricao, cumprida = :cumprida, dt_venc = :dt_venc, dt_cum' +
        'primento = :dt_cumprimento, dt_aviso = :dt_aviso, id_responsavel' +
        ' = :id_responsavel, id_executor = :id_executor, protocolo = :pro' +
        'tocolo, id_categoria = :id_categoria, prazo = :prazo, solic_praz' +
        'o = :solic_prazo, solic_desconsid = :solic_desconsid, solic_subs' +
        't = :solic_subst'
      'WHERE'
      '  id = :Old_id')
    SQLRefresh.Strings = (
      
        'SELECT id, id_licenca, numero, descricao, cumprida, dt_venc, dt_' +
        'cumprimento, dt_aviso, id_responsavel, id_executor, protocolo, i' +
        'd_categoria, prazo, solic_prazo, solic_desconsid, solic_subst FR' +
        'OM condicionante'
      'WHERE'
      '  id = :id')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM (SELECT * FROM condicionante'
      ')')
    Connection = dtm_dados.mysql_conn
    Transaction = tra
    SQL.Strings = (
      'select *'
      'from condicionante'
      'where id_licenca = :id'
      'order by numero')
    MasterSource = dts_licenca
    BeforeOpen = dse_condicionanteBeforeOpen
    BeforePost = dse_condicionanteBeforePost
    AfterPost = dse_condicionanteAfterPost
    AfterScroll = dse_condicionanteAfterScroll
    OnCalcFields = dse_condicionanteCalcFields
    OnNewRecord = dse_condicionanteNewRecord
    Left = 379
    Top = 412
    ParamData = <
      item
        DataType = ftInteger
        Name = 'id'
        ParamType = ptInput
      end>
    object dse_condicionanteid: TIntegerField
      AutoGenerateValue = arAutoInc
      FieldName = 'id'
    end
    object dse_condicionanteid_licenca: TIntegerField
      FieldName = 'id_licenca'
      Required = True
    end
    object dse_condicionantenumero: TStringField
      FieldName = 'numero'
      Size = 30
    end
    object dse_condicionantedescricao: TMemoField
      FieldName = 'descricao'
      Required = True
      BlobType = ftMemo
    end
    object dse_condicionantecumprida: TStringField
      FieldName = 'cumprida'
      FixedChar = True
      Size = 1
    end
    object dse_condicionantedt_venc: TDateField
      FieldName = 'dt_venc'
    end
    object dse_condicionantedt_cumprimento: TDateField
      FieldName = 'dt_cumprimento'
    end
    object dse_condicionantedt_aviso: TDateField
      FieldName = 'dt_aviso'
    end
    object dse_condicionanteid_responsavel: TIntegerField
      FieldName = 'id_responsavel'
    end
    object dse_condicionanteid_executor: TIntegerField
      FieldName = 'id_executor'
    end
    object dse_condicionanteprotocolo: TStringField
      FieldName = 'protocolo'
      Size = 512
    end
    object dse_condicionanteid_categoria: TIntegerField
      FieldName = 'id_categoria'
    end
    object dse_condicionantecategoria: TStringField
      FieldKind = fkCalculated
      FieldName = 'categoria'
      Size = 60
      Calculated = True
    end
    object dse_condicionanteprazo: TIntegerField
      FieldName = 'prazo'
    end
    object dse_condicionanteImg_protocolo: TBooleanField
      FieldKind = fkCalculated
      FieldName = 'Img_protocolo'
      Calculated = True
    end
    object dse_condicionantesolic_prazo: TDateField
      FieldName = 'solic_prazo'
    end
    object dse_condicionantesolic_desconsid: TDateField
      FieldName = 'solic_desconsid'
    end
    object dse_condicionantesolic_subst: TDateField
      FieldName = 'solic_subst'
    end
  end
  object tra: TUniTransaction
    DefaultConnection = dtm_dados.mysql_conn
    Left = 472
    Top = 408
  end
  object pop_abrir: TPopupMenu
    Left = 104
    Top = 32
    object mnu_open_licen: TMenuItem
      Caption = 'Licen'#231'a'
      OnClick = mnu_open_licenClick
    end
    object mnu_open_solic: TMenuItem
      Caption = 'Solicita'#231#227'o'
      OnClick = mnu_open_solicClick
    end
  end
  object pop_carregar: TPopupMenu
    Left = 56
    Top = 32
    object mnu_load_licenca: TMenuItem
      Caption = 'Licen'#231'a'
      OnClick = mnu_load_licencaClick
    end
    object mnu_load_solic: TMenuItem
      Caption = 'Solicita'#231#227'o'
      OnClick = mnu_load_solicClick
    end
  end
end
