# Generated by Django 3.1.2 on 2020-11-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=120)),
                ('fantasia', models.CharField(max_length=100)),
            ],
        ),
    ]
